language: java

matrix:
  include:
  - os: linux
    before_install:
    # to prevent IPv6 being used for APT
    - sudo bash -c "echo 'Acquire::ForceIPv4 \"true\";' > /etc/apt/apt.conf.d/99force-ipv4"
    - travis_retry sudo apt-get -y -qq update
    - travis_retry sudo apt-get install -y -qq software-properties-common python-software-properties
    - travis_retry sudo apt-add-repository -y ppa:octave/stable
    - travis_retry sudo apt-get -y -qq update
    - travis_retry sudo apt-get -y -qq install octave liboctave-dev
    - cd ..
    - rm -rf MOxUnit; #Install Octave unit test package
    - git clone https://github.com/MOxUnit/MOxUnit.git # Install MOxUnit, which adds itself to the startup path
    - make -C MOxUnit install
    - rm -rf MOcov;
    - git clone https://github.com/MOcov/MOcov.git;
    - make -C MOcov install; #Install Octave coverage report
    - cd netZooM
    - octave -q --eval "pkg install -forge io; pkg install -forge statistics; pkg install -forge nan"
  - os: osx
    before_install:
    - brew update
    - brew install octave > /dev/null
    - brew install md5sha1sum
    - cd ..
    - rm -rf MOxUnit; #Install Octave unit test package
    - git clone https://github.com/MOxUnit/MOxUnit.git # Install MOxUnit, which adds itself to the startup path
    - make -C MOxUnit install
    - rm -rf MOcov;
    - git clone https://github.com/MOcov/MOcov.git;
    - make -C MOcov install; #Install Octave coverage report
    - cd netZooM
    - octave -q --eval "pkg install -forge io; pkg install -forge statistics; pkg install -forge nan"

before_script:
- rm -f testresults.xml;
- rm -f coverage.xml;
- rm -f .coverage;
- rm -f coveralls.json;

script:
- pwd
- ls
- octave -q --eval "addpath(genpath(fullfile(pwd,'netZooM')));exit(~moxunit_runtests('tests','-recursive','-verbose','-junit_xml_file','testresults.xml','-with_coverage','-cover','netZooM','-cover_exclude','tests','-cover_xml_file','coverage.xml','-cover_json_file','coveralls.json'));"

branches:
  only:
  - master
  - devel

after_success:
- bash <(curl -s https://codecov.io/bash)
