language: c

addons:
  apt:
    pacakges:
    - octave

matrix:
  include:
  - os: linux
    language: sh
    before_install:
    - echo -ne '\n' | sudo apt-add-repository ppa:octave/stable
    - sudo apt-get update
    - sudo apt-get install octave -y
    - sudo apt-get install octave-statistics
  - os: osx
    before_install:
    - brew update
    - brew install octave > /dev/null
    - brew install octave-statistics

script:
- octave-cli tests/testNetzoo.m
