language: c

addons:
  apt:
    pacakges:
    - octave

matrix:
  include:
  - os: osx
    before_install:
    - brew update
    - brew install octave > /dev/null

script:
- travis_wait 60 octave-cli tests/testNetzoo.m

branches:
  only:
  - master
  - devel

after_success:
- bash <(curl -s https://codecov.io/bash)
