language: c

addons:
  apt:
    pacakges:
    - octave

matrix:
  include:
  - os: osx
    before_install:
    - brew update
    - brew install octave > /dev/null

before_install:
    - rm -rf MOcov;
    - git clone https://github.com/MOcov/MOcov.git;
    - make -C MOcov install; #Install Octave coverage report

script:
- pwd
- ls
- octave-cli -q --eval "addpath(genpath('tests'));mocov('-cover','netzoo-m',
            '-expression','testNetzoo',
            '-cover_json_file','coverage.json',
            '-cover_xml_file','coverage.xml',
            '-cover_html_dir','coverage_html');"

after_success:
- bash <(curl -s https://codecov.io/bash)

