language: c

addons:
  apt:
    pacakges:
    - octave

matrix:
  include:
  - os: linux
  - os: windows
    language: sh
    before_install:
    - sudo apt-add-repository ppa:octave/stable
    - sudo apt-get update
    - sudo apt-get install octave
  - os: osx
    before_install:
    - brew install octave > /dev/null

script:
- octave-cli tests/testNetzoo.m
